services:
  - type: web
    name: slowly-clone
    env: node
    buildCommand: npm install
    startCommand: npm start
    plan: free
    codeRepository:
      type: github
      url: <https://github.com/Hacker0191/pookie-letters.git>
